
import React from "react";
import { AlertTriangle, Shield } from "lucide-react";

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="divine-section section-spacing relative overflow-hidden">
      {/* Enhanced background elements */}
      <div className="absolute inset-0 divine-grid bg-[size:35px_35px] opacity-15"></div>
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-cyber-accent/10 via-cyber-accent/5 to-transparent opacity-70"></div>
      
      {/* Floating divine particles */}
      <div className="absolute top-16 left-16 w-2 h-2 bg-cyber-accent rounded-full animate-divine-float opacity-70"></div>
      <div className="absolute top-32 right-24 w-1 h-1 bg-cyber-primary rounded-full animate-ethereal-drift opacity-80"></div>
      <div className="absolute bottom-24 left-1/3 w-1.5 h-1.5 bg-cyber-secondary rounded-full animate-divine-float opacity-60"></div>
      
      <div className="content-max-width container-padding relative z-10">
        <div className="text-center max-w-4xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 bg-cyber-accent/10 border border-cyber-accent/30 px-4 py-2 rounded-full text-sm mb-6 animate-divine-pulse">
            <AlertTriangle className="w-4 h-4 text-cyber-accent" />
            <span className="divine-text font-semibold">Legal Information</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
            Legal <span className="divine-shimmer-text">Disclaimer</span>
          </h2>
        </div>
        
        <div className="max-w-5xl mx-auto divine-card divine-glow-effect">
          <div className="flex items-start gap-6 mb-8">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyber-accent/20 via-cyber-accent/10 to-transparent flex items-center justify-center shrink-0 mt-2 divine-border">
              <Shield className="w-6 h-6 text-cyber-accent" />
            </div>
            <div className="flex-1">
              <h3 className="text-2xl md:text-3xl font-semibold mb-6 divine-text">Terms of Use & Limitations of Liability</h3>
              
              <div className="space-y-6 text-cyber-muted-foreground text-base leading-relaxed">
                <p>
                  <strong className="text-cyber-accent">No Guarantees:</strong> MicroSaaS GPT provides ideas, guidance, and prompts based on AI technology, but we make no guarantees regarding the commercial success, profitability, or viability of any generated ideas. Users implement these ideas at their own risk.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Intellectual Property:</strong> Ideas generated by MicroSaaS GPT are provided for your personal use. AI Web Tools LLC makes no claim to ownership of applications you develop using our tool, but cannot guarantee the uniqueness of generated ideas. Users are responsible for conducting their own intellectual property research.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Technical Limitations:</strong> While the generated prompts are optimized for AI code builders, we cannot guarantee they will work perfectly with all platforms or that the resulting code will be error-free, secure, or optimized for all use cases. Users should review and test all generated code before deployment.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Third-Party Services:</strong> MicroSaaS GPT may suggest integration with third-party services. We are not affiliated with these services unless explicitly stated, and users are responsible for complying with their terms of service.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Use Limitations:</strong> MicroSaaS GPT should not be used to create applications that violate laws, promote harmful activities, infringe on intellectual property rights, or violate the terms of service of any platform where the application will be deployed.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Business Advice:</strong> Any business strategies, monetization plans, or marketing suggestions provided are for informational purposes only and do not constitute professional business or legal advice. Users should consult with appropriate professionals before implementing business strategies.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Limitation of Liability:</strong> AI Web Tools LLC and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of MicroSaaS GPT or any applications developed using our tool.
                </p>
                
                <p>
                  <strong className="text-cyber-accent">Changes to Service:</strong> We reserve the right to modify, suspend, or discontinue MicroSaaS GPT or any part thereof at any time without prior notice.
                </p>
                
                <p className="text-cyber-foreground font-medium border-t border-cyber-accent/20 pt-6">
                  By using MicroSaaS GPT, you acknowledge that you have read, understood, and agree to be bound by this disclaimer and our Terms of Service.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
