
import React from "react";
import { AlertTriangle, Shield } from "lucide-react";

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="py-20 relative overflow-hidden">
      {/* Background elements */}
      <div className="absolute inset-0 bg-cyber-grid bg-[size:30px_30px] opacity-10"></div>
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-cyber-muted to-transparent opacity-50"></div>
      
      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-1.5 bg-cyber-muted px-3 py-1 rounded-full text-sm mb-4">
            <AlertTriangle className="w-4 h-4 text-cyber-accent" />
            <span>Legal Information</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Legal <span className="neon-text">Disclaimer</span></h2>
        </div>
        
        <div className="max-w-4xl mx-auto glass p-8 rounded-lg border border-cyber-primary/20">
          <div className="flex items-start gap-4 mb-6">
            <Shield className="w-8 h-8 text-cyber-primary shrink-0 mt-1" />
            <div>
              <h3 className="text-xl font-semibold mb-3">Terms of Use & Limitations of Liability</h3>
              
              <div className="space-y-4 text-cyber-muted-foreground text-sm">
                <p>
                  <strong>No Guarantees:</strong> MicroSaaS GPT provides ideas, guidance, and prompts based on AI technology, but we make no guarantees regarding the commercial success, profitability, or viability of any generated ideas. Users implement these ideas at their own risk.
                </p>
                
                <p>
                  <strong>Intellectual Property:</strong> Ideas generated by MicroSaaS GPT are provided for your personal use. AI Web Tools LLC makes no claim to ownership of applications you develop using our tool, but cannot guarantee the uniqueness of generated ideas. Users are responsible for conducting their own intellectual property research.
                </p>
                
                <p>
                  <strong>Technical Limitations:</strong> While the generated prompts are optimized for AI code builders, we cannot guarantee they will work perfectly with all platforms or that the resulting code will be error-free, secure, or optimized for all use cases. Users should review and test all generated code before deployment.
                </p>
                
                <p>
                  <strong>Third-Party Services:</strong> MicroSaaS GPT may suggest integration with third-party services. We are not affiliated with these services unless explicitly stated, and users are responsible for complying with their terms of service.
                </p>
                
                <p>
                  <strong>Use Limitations:</strong> MicroSaaS GPT should not be used to create applications that violate laws, promote harmful activities, infringe on intellectual property rights, or violate the terms of service of any platform where the application will be deployed.
                </p>
                
                <p>
                  <strong>Business Advice:</strong> Any business strategies, monetization plans, or marketing suggestions provided are for informational purposes only and do not constitute professional business or legal advice. Users should consult with appropriate professionals before implementing business strategies.
                </p>
                
                <p>
                  <strong>Limitation of Liability:</strong> AI Web Tools LLC and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of MicroSaaS GPT or any applications developed using our tool.
                </p>
                
                <p>
                  <strong>Changes to Service:</strong> We reserve the right to modify, suspend, or discontinue MicroSaaS GPT or any part thereof at any time without prior notice.
                </p>
                
                <p>
                  By using MicroSaaS GPT, you acknowledge that you have read, understood, and agree to be bound by this disclaimer and our Terms of Service.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
